apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: mysql-pv-claim
spec:
    storageClassName: bdstoragecrud
    accessModes:
       - ReadWriteOnce
    resources:
        requests:
           storage: 10Gi